'use client';

import { useState } from 'react';
import {
  GitPullRequest,
  Loader2,
  CheckCircle,
  XCircle,
  AlertCircle,
  Send,
  Eye,
  FileText,
  Trash2,
  ExternalLink,
} from 'lucide-react';
import AppLayout from '@/components/AppLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import type { AuditCheckStatus } from '@/types';

type PRFile = {
  path: string;
  status: string;
  additions: number;
  deletions: number;
};

type AuditIssue = {
  file: string;
  line?: number;
  check: string;
  status: AuditCheckStatus;
  message: string;
  suggestion?: string;
  evidence?: any;
};

type PRInfo = {
  number: number;
  title: string;
  author: string;
  url: string;
  headRef: string;
  baseRef: string;
};

type ReviewComment = {
  id: string;
  path: string;
  body: string;
  line?: number;
  originalText?: string;
  suggestion?: string;
  enabled: boolean;
};

function StatusIcon({ status }: { status: AuditCheckStatus }) {
  switch (status) {
    case 'PASS':
      return <CheckCircle className="w-4 h-4 text-green-500" />;
    case 'FAIL':
      return <XCircle className="w-4 h-4 text-red-500" />;
    case 'WARN':
      return <AlertCircle className="w-4 h-4 text-yellow-500" />;
    default:
      return <AlertCircle className="w-4 h-4 text-gray-400" />;
  }
}

function StatusBadge({ status }: { status: AuditCheckStatus }) {
  const variants: Record<string, string> = {
    PASS: 'bg-green-100 text-green-700 border-green-200',
    FAIL: 'bg-red-100 text-red-700 border-red-200',
    WARN: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  };

  return (
    <span className={`text-xs px-2 py-0.5 rounded-full border ${variants[status] || 'bg-gray-100 text-gray-500'}`}>
      {status}
    </span>
  );
}

export default function PRReviewPage() {
  const { toast } = useToast();
  const [prUrl, setPrUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [prInfo, setPrInfo] = useState<PRInfo | null>(null);
  const [files, setFiles] = useState<PRFile[]>([]);
  const [issues, setIssues] = useState<AuditIssue[]>([]);
  const [comments, setComments] = useState<ReviewComment[]>([]);
  const [reviewSummary, setReviewSummary] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [published, setPublished] = useState(false);

  const fetchPR = async () => {
    if (!prUrl.trim()) return;

    setLoading(true);
    setError(null);
    setPrInfo(null);
    setFiles([]);
    setIssues([]);
    setComments([]);
    setPublished(false);

    try {
      const res = await fetch('/api/pr-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prUrl: prUrl.trim() }),
      });

      const data = await res.json();

      if (!data.ok) {
        setError(data.error || 'Failed to fetch PR');
        return;
      }

      setPrInfo(data.pr);
      setFiles(data.files || []);
      setIssues(data.issues || []);

      // Generate review comments from issues
      const newComments: ReviewComment[] = (data.issues || []).map((issue: AuditIssue, idx: number) => {
        let body = `**${issue.check}**: ${issue.message}`;
        if (issue.suggestion) {
          body += `\n\n**Suggestion:**\n\`\`\`\n${issue.suggestion}\n\`\`\``;
        }
        return {
          id: `${idx}`,
          path: issue.file,
          body,
          line: issue.line,
          originalText: issue.evidence?.original || issue.evidence?.originalText,
          suggestion: issue.suggestion,
          enabled: true,
        };
      });

      setComments(newComments);

      // Generate summary
      const failCount = (data.issues || []).filter((i: AuditIssue) => i.status === 'FAIL').length;
      const warnCount = (data.issues || []).filter((i: AuditIssue) => i.status === 'WARN').length;
      setReviewSummary(
        `## Content Audit Review\n\n` +
        `Found **${failCount}** issue(s) and **${warnCount}** warning(s) in ${data.files?.length || 0} MDX file(s).\n\n` +
        `_Review generated by Auth0-IA audit tool._`
      );

      if (data.issues?.length === 0) {
        toast({ title: 'No issues found', description: 'This PR looks good!' });
      }

    } catch (e: any) {
      setError(e?.message || 'Network error');
    } finally {
      setLoading(false);
    }
  };

  const toggleComment = (id: string) => {
    setComments(prev =>
      prev.map(c => c.id === id ? { ...c, enabled: !c.enabled } : c)
    );
  };

  const removeComment = (id: string) => {
    setComments(prev => prev.filter(c => c.id !== id));
  };

  const updateCommentBody = (id: string, body: string) => {
    setComments(prev =>
      prev.map(c => c.id === id ? { ...c, body } : c)
    );
  };

  const publishReview = async () => {
    if (!prInfo) return;

    const enabledComments = comments.filter(c => c.enabled);

    setPublishing(true);
    try {
      const res = await fetch('/api/pr-review/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prUrl,
          summary: reviewSummary,
          comments: enabledComments.map(c => ({
            path: c.path,
            body: c.body,
            line: c.line,
            originalText: c.originalText,
            suggestion: c.suggestion,
          })),
        }),
      });

      const data = await res.json();

      if (data.ok) {
        setPublished(true);
        toast({ title: 'Review published', description: 'Your review has been added to the PR' });
      } else {
        toast({ title: 'Failed to publish', description: data.error, variant: 'destructive' });
      }
    } catch (e: any) {
      toast({ title: 'Error', description: e?.message || 'Network error', variant: 'destructive' });
    } finally {
      setPublishing(false);
    }
  };

  const enabledCount = comments.filter(c => c.enabled).length;

  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2 flex items-center gap-2">
            <GitPullRequest className="w-8 h-8" />
            PR Review
          </h1>
          <p className="text-muted-foreground">
            Audit a pull request and add review comments with suggestions.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Review Pull Request</CardTitle>
            <CardDescription>
              Paste a GitHub PR URL to audit the changed MDX files.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-2">
              <Input
                value={prUrl}
                onChange={(e) => setPrUrl(e.target.value)}
                placeholder="https://github.com/auth0/docs-v2/pull/123"
                className="flex-1"
                onKeyDown={(e) => e.key === 'Enter' && fetchPR()}
              />
              <Button onClick={fetchPR} disabled={loading || !prUrl.trim()}>
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Loading...
                  </>
                ) : (
                  <>
                    <Eye className="w-4 h-4 mr-2" />
                    Fetch PR
                  </>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>

        {error && (
          <Card className="border-red-200 dark:border-red-900">
            <CardContent className="pt-6">
              <div className="flex items-center gap-2 text-red-600">
                <XCircle className="w-5 h-5" />
                <span className="font-medium">Error</span>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">{error}</p>
            </CardContent>
          </Card>
        )}

        {prInfo && (
          <>
            {/* PR Info Card */}
            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-lg">
                      #{prInfo.number}: {prInfo.title}
                    </CardTitle>
                    <CardDescription className="mt-1">
                      by <span className="font-medium">{prInfo.author}</span> · {prInfo.headRef} → {prInfo.baseRef}
                    </CardDescription>
                  </div>
                  <Button variant="outline" size="sm" asChild>
                    <a href={prInfo.url} target="_blank" rel="noreferrer">
                      <ExternalLink className="w-4 h-4 mr-2" />
                      View PR
                    </a>
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex gap-4 flex-wrap text-sm">
                  <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-muted-foreground" />
                    <span>{files.length} MDX file(s)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <XCircle className="w-4 h-4 text-red-500" />
                    <span>{issues.filter(i => i.status === 'FAIL').length} issue(s)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-yellow-500" />
                    <span>{issues.filter(i => i.status === 'WARN').length} warning(s)</span>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Files */}
            {files.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle>Changed Files</CardTitle>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="divide-y">
                    {files.map((file) => (
                      <div key={file.path} className="flex items-center gap-3 p-3">
                        <FileText className="w-4 h-4 text-muted-foreground" />
                        <span className="font-mono text-sm flex-1">{file.path}</span>
                        <Badge variant="outline" className="text-xs">
                          +{file.additions} -{file.deletions}
                        </Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Review Summary */}
            <Card>
              <CardHeader>
                <CardTitle>Review Summary</CardTitle>
                <CardDescription>
                  This will be posted as the main review comment.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={reviewSummary}
                  onChange={(e) => setReviewSummary(e.target.value)}
                  rows={5}
                  className="font-mono text-sm"
                />
              </CardContent>
            </Card>

            {/* Review Comments */}
            {comments.length > 0 && (
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle>Review Comments ({enabledCount}/{comments.length})</CardTitle>
                      <CardDescription>
                        Toggle comments to include/exclude from the review.
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="divide-y">
                    {comments.map((comment) => {
                      const issue = issues[parseInt(comment.id)];
                      return (
                        <div
                          key={comment.id}
                          className={`p-4 ${!comment.enabled ? 'opacity-50 bg-muted/30' : ''}`}
                        >
                          <div className="flex items-start gap-3">
                            <Checkbox
                              checked={comment.enabled}
                              onCheckedChange={() => toggleComment(comment.id)}
                              className="mt-1"
                            />
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 mb-2">
                                {issue && <StatusIcon status={issue.status} />}
                                <span className="font-mono text-xs text-muted-foreground">
                                  {comment.path}
                                  {comment.line && `:${comment.line}`}
                                </span>
                                {issue && <StatusBadge status={issue.status} />}
                              </div>
                              <Textarea
                                value={comment.body}
                                onChange={(e) => updateCommentBody(comment.id, e.target.value)}
                                rows={3}
                                className="font-mono text-xs"
                                disabled={!comment.enabled}
                              />
                            </div>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => removeComment(comment.id)}
                              className="text-muted-foreground hover:text-red-500"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Publish Button */}
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium">
                      {published ? 'Review Published' : 'Ready to Publish'}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      {published
                        ? 'Your review has been added to the PR.'
                        : `${enabledCount} comment(s) will be added to the PR.`}
                    </p>
                  </div>
                  {published ? (
                    <Button variant="outline" asChild>
                      <a href={prInfo.url} target="_blank" rel="noreferrer">
                        <ExternalLink className="w-4 h-4 mr-2" />
                        View on GitHub
                      </a>
                    </Button>
                  ) : (
                    <Button
                      onClick={publishReview}
                      disabled={publishing || (enabledCount === 0 && !reviewSummary.trim())}
                    >
                      {publishing ? (
                        <>
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          Publishing...
                        </>
                      ) : (
                        <>
                          <Send className="w-4 h-4 mr-2" />
                          Publish Review
                        </>
                      )}
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          </>
        )}

        {!prInfo && !loading && !error && (
          <Card className="border-dashed">
            <CardContent className="py-12 text-center text-muted-foreground">
              <GitPullRequest className="w-12 h-12 mx-auto mb-4 opacity-50" />
              <p>Enter a PR URL above to start the review</p>
            </CardContent>
          </Card>
        )}
      </div>
    </AppLayout>
  );
}
