import { NextResponse } from 'next/server';
import { z } from 'zod';
import { sql } from '@vercel/postgres';
import { requireSession } from '@/lib/session';

const BodySchema = z.object({
  filePath: z.string().min(1),
  suggestions: z.array(z.object({
    before: z.string(),
    after: z.string(),
  })),
  prTitle: z.string().optional(),
  prBody: z.string().optional(),
  targetRepo: z.string().optional(),
});

function b64encode(s: string) {
  return Buffer.from(s, 'utf8').toString('base64');
}

async function gh<T>(token: string, path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init?.headers || {}),
    },
    cache: 'no-store',
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`GitHub API error ${res.status}: ${text}`);
  }
  return (await res.json()) as T;
}

export async function POST(req: Request) {
  try {
    const { user } = await requireSession();
    const body = BodySchema.parse(await req.json());

    const ghToken = user.github_pat_decrypted || user.github_access_token_decrypted;
    const defaultTarget = process.env.MAINTENANCE_UPSTREAM_REPO || 'auth0/docs-v2';
    const targetRepo = (body.targetRepo || defaultTarget).trim();
    const [owner, repo] = targetRepo.split('/');
    if (!owner || !repo) throw new Error(`Invalid targetRepo: ${targetRepo}`);

    const baseBranch = process.env.MAINTENANCE_BASE_BRANCH || 'main';

    // 1. Get base branch SHA
    const baseRef = await gh<{ object: { sha: string } }>(
      ghToken,
      `/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`
    );
    const baseSha = baseRef.object.sha;

    // 2. Create branch
    const slug = body.filePath
      .replace(/^[./]+/, '')
      .replace(/[^a-zA-Z0-9/_-]+/g, '-')
      .slice(0, 80)
      .replace(/\//g, '-');
    const branchName = `rules-deprecation/${slug}-${Date.now()}`;

    await gh(ghToken, `/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    });

    // 3. Fetch file content
    const file = await gh<{ sha: string; content: string; encoding: string }>(
      ghToken,
      `/repos/${owner}/${repo}/contents/${encodeURIComponent(body.filePath)}?ref=${encodeURIComponent(branchName)}`
    );
    if (file.encoding !== 'base64') throw new Error(`Unexpected encoding: ${file.encoding}`);
    let content = Buffer.from(file.content.replace(/\n/g, ''), 'base64').toString('utf8');

    // 4. Apply suggestions
    let appliedCount = 0;
    for (const suggestion of body.suggestions) {
      if (suggestion.before && content.includes(suggestion.before)) {
        content = content.replace(suggestion.before, suggestion.after);
        appliedCount++;
      }
    }

    if (appliedCount === 0) {
      return NextResponse.json(
        { ok: false, error: 'No suggestions could be applied (original text not found in file).' },
        { status: 400 }
      );
    }

    // 5. Commit
    await gh(ghToken, `/repos/${owner}/${repo}/contents/${encodeURIComponent(body.filePath)}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `docs: migrate Rules to Actions in ${body.filePath.replace('main/docs/', '')}`,
        content: b64encode(content),
        sha: file.sha,
        branch: branchName,
      }),
    });

    // 6. Open PR
    const prTitle = body.prTitle || `docs: migrate Rules references to Actions in ${body.filePath.replace('main/docs/', '')}`;
    const prBodyLines = [
      '## Summary',
      '',
      `Migrates Auth0 Rules references to Auth0 Actions in \`${body.filePath.replace('main/docs/', '')}\`.`,
      '',
      `**Changes applied:** ${appliedCount} of ${body.suggestions.length} suggestions`,
      '',
      '## Changes',
      '',
      ...body.suggestions.slice(0, 10).map((s, i) => {
        if (!s.before) return `${i + 1}. Content addition`;
        const preview = s.before.slice(0, 80).replace(/\n/g, ' ');
        return `${i + 1}. \`${preview}${s.before.length > 80 ? '...' : ''}\``;
      }),
      '',
      '---',
      '',
      'Generated by auth0-ia Rules Deprecation Tracker',
    ];

    const pr = await gh<{ html_url: string; number: number }>(
      ghToken,
      `/repos/${owner}/${repo}/pulls`,
      {
        method: 'POST',
        body: JSON.stringify({
          title: prTitle,
          head: branchName,
          base: baseBranch,
          body: body.prBody || prBodyLines.join('\n'),
        }),
      }
    );

    // 7. Update status in DB
    try {
      await sql`
        CREATE TABLE IF NOT EXISTS rules_deprecation_status (
          file_path TEXT PRIMARY KEY,
          status TEXT NOT NULL DEFAULT 'pending',
          pr_url TEXT,
          notes TEXT,
          updated_by TEXT,
          updated_at TIMESTAMP DEFAULT NOW()
        )
      `;
      await sql`
        INSERT INTO rules_deprecation_status (file_path, status, pr_url, updated_by, updated_at)
        VALUES (${body.filePath}, 'in_progress', ${pr.html_url}, ${user.github_username}, NOW())
        ON CONFLICT (file_path) DO UPDATE SET
          status = 'in_progress',
          pr_url = ${pr.html_url},
          updated_by = ${user.github_username},
          updated_at = NOW()
      `;
    } catch (dbErr) {
      // Non-fatal: PR was created, just status tracking failed
      console.warn('[Rules Deprecation] DB status update failed:', dbErr);
    }

    return NextResponse.json({ ok: true, prUrl: pr.html_url, prNumber: pr.number, branchName, appliedCount });
  } catch (err: any) {
    console.error('[Rules Deprecation] open-pr error:', err);
    return NextResponse.json(
      { ok: false, error: err?.message || String(err) },
      { status: 400 }
    );
  }
}
